Repository ONSdigital/dis-wagtail, pull requests merged in 2025-07, with the labels that each got.

#281 Switch to dslr 0.5.0 and remove the need for psycopg 2 dependency
  cms/bundles/enums.py
  cms/private_media/models/mixins.py
  cms/release_calendar/enums.py
  cms/release_calendar/models.py
  functional_tests/behave_fixtures.py
  poetry.lock
  pyproject.toml
Labels: component: Dependencies 🕸️, DX

#236 Document external environment and read replica setup
  docs/custom-features/README.md
  docs/custom-features/db-read-replica.md
  docs/custom-features/deployment-environments.md
Labels: documentation

#287 Add audio description field
  cms/datavis/blocks/base.py
  cms/datavis/tests/test_chart_blocks_base.py
  cms/datavis/tests/test_scatter_plot_block.py
  functional_tests/features/statistical_article_page.feature
  functional_tests/steps/statistical_article_page.py
Labels: DataVis

#283 Add tests for get_translated_string
  cms/release_calendar/tests/test_utils.py
  cms/release_calendar/utils.py
Labels: component: Unit / Integration Tests

#290 Custom reference line, for indexed data
  cms/datavis/blocks/base.py
  cms/datavis/blocks/charts.py
  cms/datavis/tests/test_bar_column_chart_block.py
  cms/datavis/tests/test_line_chart_block.py
Labels: DataVis

#297 Fix the team index view
  cms/teams/tests/test_viewsets.py
  cms/teams/viewsets.py
Labels: bug

#308 Remove useless suppressions
  .pylintrc
  cms/articles/models.py
  cms/auth/tests/helpers.py
  cms/auth/tests/test_utils.py
  cms/datasets/tests/test_views.py
  cms/release_calendar/models.py
  cms/search/apps.py
  cms/standard_pages/models.py
  functional_tests/steps/cms_login.py
  functional_tests/steps/home_page.py
Labels: small delighter

#250 SEO Capabilities
  .secrets.baseline
  cms/articles/models.py
  cms/articles/tests/factories.py
  cms/articles/tests/test_models.py
  cms/articles/tests/test_pages.py
  cms/core/context_processors.py
  cms/core/models/base.py
  cms/core/tests/test_context_processors.py
  cms/core/tests/test_models.py
  cms/core/tests/test_pages.py
  cms/core/tests/test_utils.py
  cms/core/tests/utils.py
  cms/jinja2/templates/base.html
  cms/jinja2/templates/base_page.html
  cms/jinja2/templates/pages/information_page.html
  cms/jinja2/templates/pages/methodology_page.html
  cms/jinja2/templates/pages/release_calendar/release_calendar_page--cancelled.html
  cms/jinja2/templates/pages/release_calendar/release_calendar_page--confirmed.html
  cms/jinja2/templates/pages/release_calendar/release_calendar_page--provisional.html
  cms/jinja2/templates/pages/release_calendar/release_calendar_page.html
  cms/jinja2/templates/pages/statistical_article_page--previous-releases.html
  cms/jinja2/templates/pages/statistical_article_page--related_data.html
  cms/jinja2/templates/pages/statistical_article_page.html
  cms/jinja2/templates/pages/theme_page.html
  cms/jinja2/templates/pages/topic_page.html
  cms/navigation/jinja2tags.py
  cms/navigation/templatetags/navigation_tags.py
  cms/navigation/tests/test_navigation_tags.py
  cms/settings/base.py
  poetry.lock
  pyproject.toml
Labels: do not merge

#296 Add iframe visualisation block and refactor BaseVisualisationBlock
  cms/articles/models.py
  cms/core/blocks/section_blocks.py
  cms/datavis/blocks/__init__.py
  cms/datavis/blocks/base.py
  cms/datavis/blocks/charts.py
  cms/datavis/tests/test_chart_blocks_base.py
  cms/datavis/tests/test_iframe_block.py
  cms/settings/base.py
Labels: DataVis

#311 Disable only the global submitted notifications
  cms/users/signal_handlers.py
  cms/users/tests/test_signal_handlers.py
Labels: small delighter

#315 Add additional URL for health endpoint
  cms/core/tests/test_views.py
  cms/urls.py
Labels: component: Infrastructure 🏗️

#309 Add a Subsection Accordion
  cms/core/blocks/__init__.py
  cms/core/blocks/accordion.py
  cms/core/blocks/section_blocks.py
  cms/core/blocks/stream_blocks.py
  cms/core/tests/test_blocks.py
  cms/jinja2/templates/components/streamfield/accordion_block.html
  functional_tests/features/statistical_article_page.feature
  functional_tests/steps/statistical_article_page.py
Labels: integration: Design System

#313 Bundles - UX/user feedback tweaks, part 1
  cms/bundles/migrations/0005_bundle_updated_at.py
  cms/bundles/models.py
  cms/bundles/templates/bundles/wagtailadmin/panels/bundles_in_review.html
  cms/bundles/templates/bundles/wagtailadmin/panels/latest_bundles.html
  cms/bundles/tests/test_viewsets.py
  cms/bundles/tests/test_wagtail_hooks.py
  cms/bundles/viewsets/bundle.py
  cms/bundles/wagtail_hooks.py
  cms/settings/dev.py
  functional_tests/features/bundle_page.feature
Labels: enhancement

#316 Download the DS templates directly from the release
  scripts/load-design-system-templates.sh
Labels: DX, component: Tooling

#322 Add an optional footnotes field for charts
  cms/articles/tests/test_pages.py
  cms/datavis/blocks/base.py
  cms/datavis/tests/test_line_chart_block.py
Labels: DataVis

#328 Fix cache key for kafka token
  cms/search/publishers.py
  cms/search/tests/test_publishers.py
Labels: component: Infrastructure 🏗️

#329 Bundles - UX/user feedback tweaks, part 4 - choosers, panels and overall tidy ups
  cms/articles/models.py
  cms/articles/tests/test_models.py
  cms/articles/tests/test_pages.py
  cms/bundles/forms.py
  cms/bundles/management/commands/publish_bundles.py
  cms/bundles/mixins.py
  cms/bundles/models.py
  cms/bundles/notifications/slack.py
  cms/bundles/panels.py
  cms/bundles/templates/bundles/wagtailadmin/edit.html
  cms/bundles/templates/bundles/wagtailadmin/panels/bundles_in_review.html
  cms/bundles/templates/bundles/wagtailadmin/panels/read_only_output.html
  cms/bundles/tests/test_management_commands.py
  cms/bundles/tests/test_models.py
  cms/bundles/tests/test_pages.py
  cms/bundles/tests/test_panels.py
  cms/bundles/tests/test_signal_handlers.py
  cms/bundles/tests/test_viewsets.py
  cms/bundles/tests/test_wagtail_hooks.py
  cms/bundles/utils.py
  cms/bundles/views/add_to_bundle.py
  cms/bundles/viewsets/bundle.py
  cms/bundles/viewsets/bundle_page_chooser.py
  cms/bundles/wagtail_hooks.py
  cms/release_calendar/locks.py
  cms/release_calendar/models.py
  cms/release_calendar/tests/test_models.py
  cms/workflows/locks.py
  cms/workflows/models.py
  cms/workflows/tests/test_workflow_tweaks.py
  cms/workflows/wagtail_hooks.py
Labels: component: Bundles
