Repository ONSdigital/dis-wagtail, pull requests merged in 2025-09, with the labels that each got.

#357 Update docs-functional-tests with Sharing code between steps and step helpers
  functional_tests/README.md
Labels: Documentation

#356 Search Kafka Events: Flag Deletion/ Unpublishing of Pages
  cms/search/signal_handlers.py
  cms/search/tests/test_signal_handlers.py
  cms/settings/base.py
  docs/integrations/search_service.md
Labels: integration: External Search

#333 GTM and GA support
  cms/articles/models.py
  cms/articles/tests/test_models.py
  cms/core/analytics_utils.py
  cms/core/blocks/accordion.py
  cms/core/blocks/base.py
  cms/core/blocks/embeddable.py
  cms/core/blocks/markup.py
  cms/core/blocks/related.py
  cms/core/models/base.py
  cms/core/tests/test_analytics_utils.py
  cms/core/tests/test_blocks.py
  cms/core/tests/test_models.py
  cms/core/tests/test_pages.py
  cms/core/tests/utils.py
  cms/home/models.py
  cms/home/tests/test_models.py
  cms/jinja2/templates/base.html
  cms/jinja2/templates/pages/errors/404.html
  cms/methodology/models.py
  cms/methodology/tests/test_models.py
  cms/navigation/templatetags/navigation_tags.py
  cms/navigation/tests/test_navigation_tags.py
  cms/release_calendar/models.py
  cms/release_calendar/tests/test_models.py
  cms/standard_pages/models.py
  cms/taxonomy/models.py
  cms/taxonomy/tests/test_models.py
  cms/themes/models.py
  cms/themes/tests/test_models.py
  cms/topics/models.py
  cms/topics/tests/test_models.py
  cms/topics/tests/test_pages.py
  poetry.lock
Labels: Enhancement

#359 Topic page: links to search listing pages
  cms/jinja2/templates/pages/topic_page.html
  cms/locale/cy/LC_MESSAGES/django.po
  cms/taxonomy/models.py
  cms/taxonomy/tests/test_models.py
  cms/topics/models.py
  cms/topics/tests/test_models.py
  functional_tests/features/topic_page.feature
  functional_tests/steps/topic_page.py
Labels: New Feature
