Repository ONSdigital/dis-wagtail, pull requests merged in 2025-08, with the labels that each got.

#337 Fix navigation tags for the temporarily removed page from ThemeLinkBlock
  cms/navigation/templatetags/navigation_tags.py
Labels: bug

#335 Add locale reset to tests to avoid contamination
  cms/articles/tests/test_pages.py
  cms/core/tests/test_pages.py
  docs/README.md
  docs/troubleshooting.md
Labels: DX

#336 Fix accordion functional test by avoiding overlap
  functional_tests/steps/page_editor.py
Labels: DX

#331 Manually adding an external related article
  cms/core/tests/test_utils.py
  cms/core/utils.py
  cms/settings/dev.py
  cms/topics/migrations/0007_topicpagerelatedarticle_external_url_and_more.py
  cms/topics/models.py
  cms/topics/tests/factories.py
  cms/topics/tests/test_models.py
  functional_tests/features/topic_page_manual_related_articles.feature
  functional_tests/steps/topic_page_manual_related_articles.py
Labels: enhancement

#353 Switch to the bitnami legacy kafka image
  .github/workflows/ci.yml
  docker-compose-dev.yml
Labels: component: Tooling
