Repository ONSdigital/dis-wagtail, pull requests merged in 2025-01, with the labels that each got.

#65 Ignore vscode workspace settings files
  .gitignore
Labels: DX

#64 Disable MarkUp in megalinter
  .mega-linter.yml
Labels: DX

#81 Makefile improvements
  Makefile
Labels: DX

#79 CMS-299: Add check to ensure site settings work in external env
  cms/core/apps.py
  cms/core/checks.py
  cms/core/models/base.py
  cms/core/tests/test_settings.py
Labels: DX

#76 Update dev and test configs to streamline developer experience
  .development.env
  Makefile
  README.md
  cms/settings/dev.py
  cms/settings/test.py
Labels: DX

#92 Add video link and useful docs links to functional tests README
  functional_tests/README.md
Labels: documentation, DX

#89 Fix: Document not accessible after a page featuring it is published
  cms/private_media/models/documents.py
  cms/private_media/models/images.py
  cms/private_media/tests/test_documents.py
  cms/private_media/tests/test_images.py
  cms/private_media/tests/test_serve_views.py
  cms/private_media/views.py
  cms/settings/base.py
  cms/urls.py
  poetry.lock
  pyproject.toml
Labels: bug
