Repository ONSdigital/dis-wagtail, pull requests merged in 2025-05, with the labels that each got.

#179 Improve the language filter in custom choosers
  cms/bundles/viewsets/bundle_page_chooser.py
  cms/core/apps.py
  cms/core/forms.py
  cms/core/monkey_patches.py
  cms/core/templates/wagtailadmin/tables/locale_cell.html
  cms/core/ui.py
  cms/core/viewsets.py
  cms/navigation/wagtail_hooks.py
  cms/release_calendar/viewsets.py
  cms/topics/viewsets/featured_series.py
  cms/topics/viewsets/highlighted_items.py
  cms/topics/viewsets/series_with_headline_figures.py
Labels: small delighter

#175 Chore: charts code cleanup
  cms/core/tests/test_tags.py
  cms/datavis/blocks/base.py
  cms/datavis/blocks/charts.py
Labels: DataVis

#177 Add configurable chart aspect ratios
  cms/datavis/blocks/base.py
  cms/datavis/blocks/chart_options.py
  cms/datavis/tests/test_chart_blocks.py
  cms/datavis/tests/test_chart_options.py
  cms/jinja2/templates/components/streamfield/datavis/base_highcharts_chart_block.html
Labels: DataVis

#181 Improve headline figures on topic pages
  cms/articles/forms.py
  cms/articles/migrations/0005_statisticalarticlepage_restucture_headline_figures.py
  cms/articles/models.py
  cms/articles/tests/test_models.py
  cms/articles/tests/test_pages.py
  cms/core/blocks/__init__.py
  cms/core/blocks/headline_figures.py
  cms/core/static/js/blocks/headline-figures-item-block.js
  cms/jinja2/templates/components/streamfield/headline_figures_block.html
  cms/jinja2/templates/components/streamfield/headline_figures_item_block.html
  cms/jinja2/templates/components/streamfield/topic_headline_figure_block.html
  cms/jinja2/templates/components/streamfield/topic_headline_figures_block.html
  cms/jinja2/templates/pages/statistical_article_page.html
  cms/jinja2/templates/pages/topic_page.html
  cms/topics/blocks.py
  cms/topics/migrations/0005_topicpage_rename_headline_figures_type.py
  cms/topics/models.py
  cms/topics/static/topics/js/headline-figure-block.js
  cms/topics/tests/test_models.py
  cms/topics/tests/test_pages.py
  cms/topics/tests/test_viewsets.py
  cms/topics/viewsets/series_with_headline_figures.py
  functional_tests/steps/statistical_article_page.py
Labels: small delighter

#185 Upgrade design system to latest version (72.7.0 -> 72.9.1)
  .design-system-version
Labels: component: Dependencies 🕸️, front-end

#118 Kubernetes Deployment
  .docker/Makefile
  cms/core/cache.py
  cms/core/elasticache.py
  cms/core/tests/test_elasticache.py
  cms/core/tests/test_views.py
  cms/core/views.py
  cms/settings/base.py
  cms/urls.py
  poetry.lock
  pyproject.toml
Labels: component: Infrastructure 🏗️

#187 Add retry for restoring snapshot in behave_fixtures
  functional_tests/behave_fixtures.py
Labels: UI Tests Errors/ Flakiness Being Fixed

#165 Add statistical article related data page
  cms/articles/enums.py
  cms/articles/migrations/0006_statisticalarticlepage_dataset_sorting_and_more.py
  cms/articles/models.py
  cms/articles/signal_handlers.py
  cms/articles/tests/test_models.py
  cms/articles/tests/test_pages.py
  cms/datasets/models.py
  cms/datasets/tests/test_blocks.py
  cms/jinja2/templates/pages/statistical_article_page--related_data.html
  cms/jinja2/templates/pages/statistical_article_page.html
  cms/navigation/templatetags/navigation_tags.py
  cms/settings/base.py
  cms/settings/dev.py
  cms/workflows/tests/test_workflow_tweaks.py
  functional_tests/features/statistical_article_page.feature
  functional_tests/steps/datasets.py
  functional_tests/steps/release_page.py
  functional_tests/steps/statistical_article_page.py
Labels: integration: Data API

#186 Update card component for headline figures in articles
  cms/articles/tests/test_models.py
  cms/jinja2/templates/components/streamfield/headline_figures_item_block.html
  cms/jinja2/templates/pages/statistical_article_page.html
  cms/jinja2/templates/pages/topic_page.html
Labels: integration: Design System

#162 Update methodology & topic pages - integrate with design system
  cms/articles/tests/test_pages.py
  cms/jinja2/templates/pages/methodology_page.html
  cms/jinja2/templates/pages/statistical_article_page.html
  cms/jinja2/templates/pages/topic_page.html
  cms/methodology/tests/test_pages.py
  cms/topics/tests/test_pages.py
Labels: front-end, integration: Design System

#194 Refactor tests and business logic to use named objects
  cms/datavis/blocks/base.py
  cms/datavis/blocks/charts.py
  cms/datavis/tests/test_chart_blocks.py
Labels: DataVis

#193 Accessibility: HTML Validation Fixes
  cms/jinja2/templates/components/accredited/accredited-logo.html
  cms/jinja2/templates/components/census/census-logo.html
  cms/jinja2/templates/components/streamfield/glossary_section_block.html
  cms/jinja2/templates/pages/methodology_page.html
  cms/jinja2/templates/pages/statistical_article_page.html
Labels: bug, front-end, component: Performance 🚀

#189 Ensure dockerignore matches gitignore
  .dockerignore
  .github/check_docker_ignore.py
  .github/workflows/ci.yml
  .gitignore
  Makefile
  cms/settings/.gitignore
Labels: DX, component: Tooling

#200 Feature/statistical article page chart ccb 103
  cms/core/blocks/section_blocks.py
  cms/datavis/apps.py
  cms/datavis/blocks/base.py
  cms/datavis/checks.py
  cms/datavis/models/mixins.py
  cms/standard_pages/models.py
Labels: DataVis

#192 Add non-js equation generation
  .github/workflows/ci.yml
  Dockerfile
  cms/articles/forms.py
  cms/articles/tests/test_models.py
  cms/core/blocks/equation.py
  cms/core/blocks/section_blocks.py
  cms/core/blocks/stream_blocks.py
  cms/core/checks.py
  cms/core/forms.py
  cms/core/static/js/blocks/equation-block.js
  cms/core/tests/test_utils.py
  cms/core/utils.py
  cms/jinja2/templates/components/streamfield/equation_block.html
  cms/methodology/models.py
  cms/standard_pages/models.py
  functional_tests/environment.py
  functional_tests/features/javascript_disabled.feature
  functional_tests/features/statistical_article_page.feature
  functional_tests/steps/information_page.py
  functional_tests/steps/javascript_disabled.py
  functional_tests/steps/statistical_article_page.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#207 Update design system version to latest release
  .design-system-version
Labels: component: Dependencies 🕸️, front-end

#205 Scatter plot
  cms/core/blocks/stream_blocks.py
  cms/datavis/blocks/__init__.py
  cms/datavis/blocks/annotations.py
  cms/datavis/blocks/base.py
  cms/datavis/blocks/charts.py
  cms/datavis/constants.py
  cms/datavis/tests/test_annotations.py
  cms/datavis/tests/test_bar_column_chart_block.py
  cms/datavis/tests/test_chart_blocks_base.py
  cms/datavis/tests/test_chart_options.py
  cms/datavis/tests/test_line_chart_block.py
  cms/datavis/tests/test_scatter_plot_block.py
Labels: DataVis

#202 Add healthcheck endpoint
  .docker/Makefile
  Dockerfile
  Makefile
  cms/core/tests/test_views.py
  cms/core/views.py
  cms/settings/base.py
  cms/settings/dev.py
  cms/urls.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: component: Infrastructure 🏗️

#211 Area chart
  cms/core/blocks/section_blocks.py
  cms/datavis/blocks/__init__.py
  cms/datavis/blocks/charts.py
  cms/datavis/constants.py
  cms/datavis/tests/test_area_chart_block.py
Labels: DataVis

#214 Configure mobile/desktop tick interval independently
  cms/datavis/blocks/base.py
  cms/datavis/blocks/charts.py
  cms/datavis/tests/test_bar_column_chart_block.py
  cms/datavis/tests/test_chart_blocks_base.py
  cms/datavis/tests/test_line_chart_block.py
  cms/datavis/tests/test_scatter_plot_block.py
Labels: DataVis

#212 Integrate header with DS component
  cms/jinja2/component_overrides/header/_macro.njk
  cms/jinja2/templates/base.html
  cms/navigation/templatetags/navigation_tags.py
  cms/navigation/tests/test_navigation_tags.py
  cms/static_src/sass/components/_navigation.scss
  cms/static_src/sass/main.scss
Labels: integration: Design System

#201 View all data & previous releases DS integration
  cms/articles/tests/test_models.py
  cms/jinja2/templates/base.html
  cms/jinja2/templates/pages/statistical_article_page--previous-releases.html
  cms/jinja2/templates/pages/statistical_article_page--related_data.html
  cms/jinja2/templates/pages/statistical_article_page.html
Labels: front-end, integration: Design System

#204 Streamfield DS integration & updates
  cms/core/blocks/base.py
  cms/core/blocks/embeddable.py
  cms/core/blocks/related.py
  cms/core/blocks/stream_blocks.py
  cms/core/tests/test_blocks.py
  cms/jinja2/templates/components/streamfield/related_links_block.html
Labels: integration: Design System
